### ISSUE TITLE
Crash at map server

### ISSUE THREAD

**Issue by haarenas** [dastgirp/eBG#11]
While doing a test something crashed the map server. The only mode active was Flavius CTF (all other modes where disabled)

This is the log:
```
#0  0x000000000062c840 in hplugin_data_store_validate (type=HPDT_MSD, 
    storeptr=0x7fff2464b358, initialize=false) at HPM.c:245 
No locals. 
#1  0x000000000062a83e in hplugins_getFromHPData (type=HPDT_MSD, pluginID=2, 
    store=0x6e61722073616820, classid=0) at HPM.c:306 
        i = 4942081 
#2  0x00007fe691606c6a in pdb_search (sd=0x2fe5c60, create=88) 
    at ExtendedBG.c:611 
        __func__ = "pdb_search" 
#3  0x00007fe69160e480 in send_bg_memberlist (sd=0x2fe5c60) 
    at ExtendedBG.c:3699 
        c = 6 
        psd = 0x2fe5c60 
#4  0x00007fe69161fb4e in bg_e_team_join (bg_id=273310640, sd=0x14e28390, 
    guild_id=0) at ExtendedBG.c:3266 
        pl_sd = 0x104a63b0 
        i = 0 
        data = 0xe28a5d0 
        bg_data_t = 0xc74b00 <clif> 
#5  0x00007fe691620264 in buildin_bg_e_join_team (st=0x7fe692a492b4) 
    at ScriptCommands.inc:408 
        sd = 0x14e28390 
        team_id = 2 
        guild_id = 2  
```

PS: VIRT_GUILD is **NOT** commented in eBG_common.h
PS2: Its a segmentation fault error

**Comment by dastgirp** [comment]
Might be some race condition. cannot find the root cause yet.
